name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run Tests by maven comand line
        default: mvn clean test
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Install Allure CLI
      run: sudo npm install -g allure-commandline --unsafe-perm=true
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run Test
      run: ${{github.event.inputs.cli}}

    - name: Generate Allure Report
      run: |
          allure generate target/allure-results --clean -o allure-report

    #- name: Upload Allure Report as artifact
      #uses: actions/upload-artifact@v4
      #with:
        #name: allure-report
        #path: allure-report

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
